# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decl_men', models.CharField(max_length=200, verbose_name='Declaraci\xf3n Mensual')),
                ('slug', models.SlugField(unique=True)),
                ('planilla', models.CharField(max_length=200, verbose_name='Planilla')),
                ('balanc_gen', models.CharField(max_length=200, verbose_name='Balance General')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Detalle del Cobro')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de Pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Monto S/.')),
                ('periodo', models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], max_length=10, verbose_name='Periodo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('cobro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobranzas.Cobro')),
            ],
        ),
    ]
