# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobro',
            name='anio',
            field=models.CharField(default=1, max_length=4, verbose_name='A\xf1o'),
            preserve_default=False,
        ),
    ]
