# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('r_social', models.CharField(max_length=100, verbose_name='Razon Social')),
                ('ruc', models.CharField(max_length=11, verbose_name='RUC')),
                ('usuario', models.CharField(max_length=50, verbose_name='Usuario')),
                ('clave_sol', models.CharField(max_length=20, verbose_name='Clave Sol')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Suspencion', 'Suspencion'), ('Baja', 'Baja Definitiva')], max_length=10, verbose_name='Estado')),
                ('regimen', models.CharField(choices=[('General', 'General'), ('Especial', 'Especial')], max_length=8, verbose_name='Regimen')),
            ],
        ),
    ]
