# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_cliente_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoLibro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro', models.CharField(choices=[('Registro de Compras', 'Registro de Compras'), ('Registro de Ventas', 'Registro de Ventas'), ('Libro Diario', 'Libro Diario'), ('Libro Mayor', 'Libro Mayor'), ('Libro de Inventario y Balances', 'Libro de Inventario y Balances'), ('Libro Caja Banco', 'Libro Caja Banco'), ('Libro Diario Simplificado', 'Libro Diario Simplificado'), ('Libro de Retenciones', 'Libro de Retenciones'), ('Registro de activos fijos', 'Registro de activos fijos'), ('Registro de Costos', 'Registro de Costos'), ('Registro de Inventario permanente de unidades f\xedsicas', 'Registro de Inventario permanente de unidades f\xedsicas'), ('Registro de Inventario permanente Valorizado', 'Registro de Inventario permanente Valorizado')], max_length=54, verbose_name='Libro de Contabilidad')),
                ('num_serie', models.PositiveIntegerField(verbose_name='N\xfamero de Serie')),
                ('num_paginas', models.PositiveIntegerField(verbose_name='N\xfamero de Paginas')),
                ('fecha_leg', models.DateField(verbose_name='Fecha de Legalizaci\xf3n')),
                ('fecha_mod', models.DateField(verbose_name='Fecha de Modificaci\xf3n')),
                ('num_hojas', models.PositiveIntegerField(verbose_name='N\xfamero de hojas')),
                ('fecha_vence', models.DateField(verbose_name='Fecha de Vencimiento')),
            ],
        ),
        migrations.CreateModel(
            name='UIT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uit', models.CharField(choices=[('UIT 150', 'UIT 150'), ('UIT 500', 'UIT 500'), ('UIT 1700', 'UIT 1700'), ('UIT > 1700', 'UIT > 1700')], default='UIT 150', max_length=10, verbose_name='UIT')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
            ],
        ),
        migrations.AddField(
            model_name='tipolibro',
            name='uit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.UIT'),
        ),
    ]
